"""
Django settings for alpacuna project.

Generated by 'django-admin startproject' using Django 1.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

from unipath import Path
PROJECT_ROOT = Path(__file__).ancestor(3)

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'ig0ql-hh91utr9bnd(vu*^&z17kvihhf3p=xf*$^zgyd8ymkck'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'django.contrib.staticfiles.finders.FileSystemFinder',
)

# Application definition

INSTALLED_APPS = (
    'grappelli.dashboard',
    'grappelli',
    'django.contrib.admin',
    'django.contrib.admindocs',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'storages',
    'south',
    'debug_toolbar',
    'apps.pages',
    'apps.categories',
    'apps.products',
    'apps.media',
    'apps.users'
    # 'material',
    # 'material.admin',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'apps.core.extra.middleware.AdminLocaleURLMiddleware',
    # 'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'alpacuna.urls.main'


GRAPPELLI_INDEX_DASHBOARD = 'alpacuna.dashboard.CustomIndexDashboard'

TEMPLATE_CONTEXT_PROCESSORS = (
    "django.core.context_processors.debug",
    "django.core.context_processors.static",
    "django.core.context_processors.request",
    "django.core.context_processors.media",
    "django.contrib.messages.context_processors.messages",
    "django.contrib.auth.context_processors.auth",
)


WSGI_APPLICATION = 'alpacuna.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': 'dbalpacuna',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': '',
        'PORT': ''
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

ADMIN_LANGUAGE_CODE = 'es'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = (
    PROJECT_ROOT.child('static'),
)

TEMPLATE_DIRS = (
    PROJECT_ROOT.child('templates'),
)

AWS_ACCESS_KEY_ID = 'ADD_KEY'
AWS_SECRET_ACCESS_KEY = 'ADD_KEY'
AWS_STORAGE_BUCKET_NAME = 'ADD_BUCKET_NAME'

S3_URL = 'http://%s.s3.amazonaws.com' % AWS_STORAGE_BUCKET_NAME
MEDIA_URL = '/media/'


USE_S3 = False
if USE_S3:
    STATICFILES_STORAGE = 'storages.backends.s3boto.S3BotoStorage'

DEFAULT_FILE_STORAGE = 'storages.backends.s3boto.S3BotoStorage'
THUMBNAIL_DEFAULT_STORAGE = 'storages.backends.s3boto.S3BotoStorage'

# MEDIA_URL = S3_URL + MEDIA_DIRECTORY


MEDIA_ROOT = PROJECT_ROOT.child('media')
STATIC_ROOT = PROJECT_ROOT.child("collected_static")


GRAPPELLI_ADMIN_TITLE = "Alpacuna"
GRAPPELLI_CLEAN_INPUT_TYPES = True


"""
GRAPPELLI_INDEX_DASHBOARD = {  # alternative method
    #'alpacuna.admin.admin_site': 'alpacuna.my_dashboard.CustomIndexDashboard',
    'django.contrib.admin.site': 'alpacuna.dashboard.CustomIndexDashboard',
}
"""
